module.exports = {
    ASSET_API: 'master-assetapi.scaffold-workers-ext-main-us.m.cld.octavelive.com',
    CAMPAIGN_API: 'campaign-api.apps.playnetwork.com',
    CLAIM_API: 'master-claim-api.apps.playnetwork.com',
    CONTENT_API: 'content-api.apps.playnetwork.com',
    CLOUDFRONT: 'cdn.apps.playnetwork.com',
    CURIO_MUSIC_API: 'curio-music-api.apps.playnetwork.com',
    CURIO_SETTINGS_API: 'curio-settings-api.apps.playnetwork.com',
    DEVICE_API: 'device-api.apps.playnetwork.com',
    KEY_API: 'key-api.apps.playnetwork.com',
    LOCATION_API: 'location-api.apps.playnetwork.com',
    LOCATION_RELATIONSHIPS_API: 'location-relationships-api.apps.playnetwork.com',
    PLAYBACK_API: 'master-playback-api.apps.playnetwork.com',
    PLAYER_SVC: 'player-svc.apps.playnetwork.com',
    PROVISION_API: 'provision-api.apps.playnetwork.com',
    STATION_API: 'master-stationapi.scaffold-workers-ext-main-us.m.cld.octavelive.com',
    DOCKER_REGISTRY: 'index.docker.io',
    PLAYNETWORK_REGISTRY: 'registry.apps.playnetwork.com',
    UBUNTU_NTP: 'ntp.ubuntu.com'
};