module.exports = {
    ASSET_API: 'master-assetapi.scaffold-workers-ext-main-us.m.cld.octavelive.com/v1/version',
    CAMPAIGN_API: 'campaign-api.apps.playnetwork.com',
    CLAIM_API: 'master-claim-api.apps.playnetwork.com/v0/version',
    CONTENT_API: 'content-api.apps.playnetwork.com',
    CLOUDFRONT: 'd3pquepjmipynj.cloudfront.net/ping.txt',
    CURIO_MUSIC_API: 'curio-music-api.apps.playnetwork.com',
    CURIO_SETTINGS_API: 'master-curio-settings-api.apps.playnetwork.com/v0/version',
    DEVICE_API: 'master-device-api.apps.playnetwork.com/v0/version',
    KEY_API: 'key-api.apps.playnetwork.com/v0/version',
    LOCATION_API: 'location-api.apps.playnetwork.com',
    LOCATION_RELATIONSHIPS_API: 'location-relationships-api.apps.playnetwork.com',
    PLAYBACK_API: 'master-playback-api.apps.playnetwork.com/v1/version',
    PLAYER_SVC: 'master-player-svc.apps.playnetwork.com',
    PROVISION_API: 'master-provision-api.apps.playnetwork.com/v1/version',
    STATION_API: 'master-stationapi.scaffold-workers-ext-main-us.m.cld.octavelive.com/v3/version',
    DOCKER_REGISTRY: 'index.docker.io',
    PLAYNETWORK_REGISTRY: 'registry.apps.playnetwork.com',
    UBUNTU_NTP: 'ntp.ubuntu.com'
};